name: Metrics
on:
  # Schedule updates (every other hour)
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Render metrics image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: cgobat
          template: classic
          base: header, activity, community, repositories
          config_timezone: Etc/UTC
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook, mathematica, html
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
